# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_packages:
  - covr
before_install:
  - sudo apt-get install libglu1-mesa-dev
  - sudo apt-get install libcgal-dev
  - sudo apt-get install libx11-dev  
  
after_success:
  - Rscript -e 'covr::codecov()'
