# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  - RGL_USE_NULL=TRUE

r_packages:
  - covr
before_install:
  - sudo apt-get install libglu1-mesa-dev
  - sudo apt-get install libcgal-dev
  - sudo apt-get install libx11-dev  
  
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

after_success:
   - Rscript -e 'covr::codecov()'
