# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  # - C:\RLibrary

# Adapt as necessary starting from here
environment:
  global:
    R_ARCH: x64
    # Need to enable when installing GitHub dependency packages.
    USE_RTOOLS: true
    R_REMOTES_STANDALONE: true
    # Set the build matrix to use R-devel, otherwise Bioconductor checks will fail
    # because the image now expects BioC 3.9 on R 3.6.
    # https://github.com/krlmlr/r-appveyor/issues/144
  matrix:
    - configuration: 3.5
      R_VERSION: 3.5.3
    - configuration: 3.6
      R_VERSION: 3.6.0

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
